//-------------------------------------------------------------------------
// ALU_Custom.v
//-------------------------------------------------------------------------
// This file is generated by PyMTL SystemVerilog translation pass.

// PyMTL Component ALU Definition
// Full name: ALU_noparam
// At c:\Users\egroj\Downloads\TFGCODIGO\Capacidades-3.1_&_3.2\ALU.py

module ALU_Custom
(
  input  logic [0:0] clk ,
  input  logic [1:0] fn ,
  input  logic [7:0] in0 ,
  input  logic [7:0] in1 ,
  output logic [7:0] out ,
  input  logic [0:0] reset 
);

  // PyMTL Update Block Source
  // At c:\Users\egroj\Downloads\TFGCODIGO\Capacidades-3.1_&_3.2\ALU.py:12
  // @update
  // def up_alu():
  //     if s.fn == 0:
  //         s.out @= s.in0 + s.in1
  //     elif s.fn == 1:
  //         s.out @= s.in0 - s.in1
  //     elif s.fn == 2:
  //         s.out @= s.in0 & s.in1
  //     elif s.fn == 3:
  //         s.out @= ~s.in0 + 1
  //     else:
  //         s.out @= 0
  
  always_comb begin : up_alu
    if ( fn == 2'd0 ) begin
      out = in0 + in1;
    end
    else if ( fn == 2'd1 ) begin
      out = in0 - in1;
    end
    else if ( fn == 2'd2 ) begin
      out = in0 & in1;
    end
    else if ( fn == 2'd3 ) begin
      out = ( ~in0 ) + 8'd1;
    end
    else
      out = 8'd0;
  end

endmodule
